title: Andrew Hercules
email: andrewhercules@gmail.com
description: The personal website of Andrew Hercules
author: Andrew Hercules
url: "http://andrewhercules.com"

twitter_username:  AndrewHercules
github_username:   AndrewHercules
linkedin_username: AndrewHercules
