baseurl: ""
url: ""

permalink: pretty

# Portfolio
collections:
  portfolio:
    output: true

# Navigation on posts and portfolio items
post_navigation: true

#Pagination
paginate: 5
paginate_path: "/blog/page:num"


# Plugins
plugins: [jekyll-paginate]

#Google Analytics
google_analytics_tracking_id: "UA-119668009-1"

# Build Settings

markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
